const ansatte = [
    { navn: "Siril Bergum", epost: "siril.bergum@kristiansand.kommune.no", paloggingsmail: "93siril@ikrs.no", kontaktlaerer: "", trinn: [] },
    { navn: "Christine Sørli", epost: "christine.sorli2@kristiansand.kommune.no", paloggingsmail: "94christine1@ikrs.no", kontaktlaerer: "", trinn: [] },
    { navn: "Janne Braadland", epost: "janne.braadland@kristiansand.kommune.no", paloggingsmail: "72janne@ikrs.no", kontaktlaerer: "adm", trinn: [] },
    { navn: "Tor Skarprud", epost: "tor.skarprud@kristiansand.kommune.no", paloggingsmail: "77tor@ikrs.no", kontaktlaerer: "adm", trinn: [] },
    { navn: "Thomas Dyrdahl", epost: "thomas.dyrdahl@kristiansand.kommune.no", paloggingsmail: "75thomas@ikrs.no", kontaktlaerer: "adm", trinn: [] },
    { navn: "Geir Andre Birkeland", epost: "geir.andre.birkeland@kristiansand.kommune.no", paloggingsmail: "71geir2@ikrs.no", kontaktlaerer: "1A", trinn: [1] },
    { navn: "Åse Reidun Svaland Kregnes", epost: "ase.reidun.svaland.kregnes@kristiansand.kommune.no", paloggingsmail: "67ase2@ikrs.no", kontaktlaerer: "1B", trinn: [1] },
    { navn: "Markus Sundgot Kristiansen", epost: "markus.sundgot.kristiansen@kristiansand.kommune.no", paloggingsmail: "93markus1@ikrs.no", kontaktlaerer: "1C", trinn: [1] },
    { navn: "Filip Madsen Tysland", epost: "filip.madsen.tysland@kristiansand.kommune.no", paloggingsmail: "92filip1@ikrs.no", kontaktlaerer: "", trinn: [1] },
    { navn: "Eddy Elisabeth Steinfeld Hallberg", epost: "eddy.elisabeth.steinfeld.hallberg@kristiansand.kommune.no", paloggingsmail: "60eddy@ikrs.no", kontaktlaerer: "", trinn: [1] },
    { navn: "Monica Gunther", epost: "monica.gunther@kristiansand.kommune.no", paloggingsmail: "75monica@ikrs.no", kontaktlaerer: "", trinn: [1] },
    { navn: "Anders Lossius", epost: "anders.lossius@kristiansand.kommune.no", paloggingsmail: "95anders5@ikrs.no", kontaktlaerer: "2A", trinn: [2] },
    { navn: "Tonje Eie Nordbø", epost: "tonje.eie.nordbo@kristiansand.kommune.no", paloggingsmail: "89tonje@ikrs.no", kontaktlaerer: "2B", trinn: [2] },
    { navn: "Silje Merete Vigemyr-Karlsen", epost: "silje.merete.vigemyr.karlsen@kristiansand.kommune.no", paloggingsmail: "82silje2@ikrs.no", kontaktlaerer: "2C", trinn: [2] },
    { navn: "Ingrid Hanne Sandvær Landa", epost: "ingrid.hanne.sandvar.landa@kristiansand.kommune.no", paloggingsmail: "71ingrid@ikrs.no", kontaktlaerer: "", trinn: [2] },
    { navn: "Hanne Løvaas", epost: "hanne.lovaas@kristiansand.kommune.no", paloggingsmail: "99hanne6@ikrs.no", kontaktlaerer: "", trinn: [2] },
    { navn: "Truls Abrahamsen", epost: "truls.abrahamsen@kristiansand.kommune.no", paloggingsmail: "97truls@ikrs.no", kontaktlaerer: "3A", trinn: [3] },
    { navn: "Daniel Rossevatn", epost: "daniel.rossevatn@kristiansand.kommune.no", paloggingsmail: "98daniel19@ikrs.no", kontaktlaerer: "3B", trinn: [3] },
    { navn: "Malin Aadnevik", epost: "malin.aadnevik@kristiansand.kommune.no", paloggingsmail: "97malin10@ikrs.no", kontaktlaerer: "3C", trinn: [3] },
    { navn: "Arian Nawzad Tawfiq", epost: "arian.nawzad.tawfiq@kristiansand.kommune.no", paloggingsmail: "96arian@ikrs.no", kontaktlaerer: "", trinn: [3] },
    { navn: "Ingrid Dahle", epost: "ingrid.dahle@kristiansand.kommune.no", paloggingsmail: "92ingrid@ikrs.no", kontaktlaerer: "", trinn: [3] },
    { navn: "Thomas Brænde Omholt", epost: "thomas.braende.omholt@kristiansand.kommune.no", paloggingsmail: "85thomas@ikrs.no", kontaktlaerer: "4A", trinn: [4] },
    { navn: "Oliv Smeland", epost: "oliv.smeland@kristiansand.kommune.no", paloggingsmail: "96smeland@ikrs.no", kontaktlaerer: "4B", trinn: [4] },
    { navn: "Espen N Nesse", epost: "espen.n.nesse@kristiansand.kommune.no", paloggingsmail: "94espen@ikrs.no", kontaktlaerer: "4C", trinn: [4] },
    { navn: "Rune Heggland", epost: "rune.heggland@kristiansand.kommune.no", paloggingsmail: "88rune@ikrs.no", kontaktlaerer: "", trinn: [4, 6] },
    { navn: "Anne Abelsen", epost: "anne.abelsen@kristiansand.kommune.no", paloggingsmail: "74anne5@ikrs.no", kontaktlaerer: "", trinn: [4, 6] },
    { navn: "Martin Myklebust", epost: "martin.myklebust@kristiansand.kommune.no", paloggingsmail: "marmyk@ikrs.no", kontaktlaerer: "5A", trinn: [5] },
    { navn: "Irene Skram", epost: "irene.skram@kristiansand.kommune.no", paloggingsmail: "64irene@ikrs.no", kontaktlaerer: "5B", trinn: [5] },
    { navn: "Ole Helge Santiago Skavlan", epost: "ole.helge.santiago.skavlan@kristiansand.kommune.no", paloggingsmail: "96ole8@ikrs.no", kontaktlaerer: "5C", trinn: [5] },
    { navn: "Heidi Johannessen", epost: "heidi.johannessen@kristiansand.kommune.no", paloggingsmail: "82heidi@ikrs.no", kontaktlaerer: "5D", trinn: [5] },
    { navn: "Hans-Petter Berg", epost: "hans-petter.berg3@kristiansand.kommune.no", paloggingsmail: "64hans@ikrs.no", kontaktlaerer: "", trinn: [5] },
    { navn: "Mari Nordby Sveberg", epost: "mari.nordby.sveberg@kristiansand.kommune.no", paloggingsmail: "94mari@ikrs.no", kontaktlaerer: "", trinn: [5] },
    { navn: "Camilla Bisseth-Isefjær", epost: "camilla.bisseth-isefjar@kristiansand.kommune.no", paloggingsmail: "92camilla@ikrs.no", kontaktlaerer: "6A", trinn: [6] },
    { navn: "Marte Schellhorn", epost: "marteschellhorn@hotmail.com", paloggingsmail: "98marte3@ikrs.no", kontaktlaerer: "6B", trinn: [6] },
    { navn: "Håvard Solli-Kleivset", epost: "havard.kleivset@kristiansand.kommune.no", paloggingsmail: "havkle@ikrs.no", kontaktlaerer: "6C", trinn: [6] },
    { navn: "Arild Røyseland", epost: "arild.royseland@kristiansand.kommune.no", paloggingsmail: "72arild@ikrs.no", kontaktlaerer: "", trinn: [6] },
    { navn: "Gro Anita Pedersen", epost: "gro.anita.pedersen@kristiansand.kommune.no", paloggingsmail: "70gro@ikrs.no", kontaktlaerer: "7A", trinn: [7] },
    { navn: "Ole-Johan Ryghseter", epost: "ole-johan.ryghseter@kristiansand.kommune.no", paloggingsmail: "76ole@ikrs.no", kontaktlaerer: "7B", trinn: [7] },
    { navn: "Lars Rosseland Knutson", epost: "lars.rosseland.knutson@kristiansand.kommune.no", paloggingsmail: "84lars2@ikrs.no", kontaktlaerer: "7C", trinn: [7] },
    { navn: "Guro Haaland", epost: "guro.haaland@kristiansand.kommune.no", paloggingsmail: "93guro@ikrs.no", kontaktlaerer: "", trinn: [7] },
    { navn: "Malika S Rasukhanova", epost: "malika.s.rasukhanova@kristiansand.kommune.no", paloggingsmail: "68malika@ikrs.no", kontaktlaerer: "", trinn: [7] }
];