let elevRegister = {
   
 // 1. TRINN (Startet 2026)
"Testesen, Tester": { startTrinn: 1, startKlasse: 'A', startAar: 2026 },



 // 1. TRINN (Startet 2025)
    "Albert, William Denstad": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Barria, Cristiano": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Fossheim, Ellie Synnøve Helland": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Gudane, Isaac Ibrahim": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Halvorsen, Sindre Stensvold": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Hussain, Iman": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Høiberg, Isabel Cornejo": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Johansen, Emmeli": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Kasin-Hansen, Nikolai Alexander": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Krumm, Thale Barria": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Kvarsnes, Matheus De Souza": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Salazar, Samuel": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Seljelund, Selma Mæhle": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Simonsen-Solem, Emma": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Timenes, Tomine": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Tvedt, Linus Brådland": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Aabel, Vetle Jahnsen": { startTrinn: 1, startKlasse: 'A', startAar: 2025 },
    "Bisseth-Isefjær, Charlotte": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Cascampas, Philippa Elea": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Chhoeuk, Eira Tveter": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Hansen, Matheo Løvheim": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Håbesland, Letizia": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Ilyas, Raima": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Jaferi, David": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Jahnsson-Rasmussen, Luis": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Jorkjend, Magnus": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Kloster, Ola Rekve": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Kristiansen, Alma": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Osland, Elida": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Qvale, Noah Nesland": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Said, Hanna Abdirisak": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Seland, Fride Vikingsdal": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Skeie, Oliver Aagaard": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Solberg, Eva Olivia": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Vold-Mørch, Ole": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Zec, Sofia Alexandra": { startTrinn: 1, startKlasse: 'B', startAar: 2025 },
    "Agyemang, Esther Nana Akyaa": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Albert, Emmely Karin": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Andersen-Fleming, Camilla": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Askland, Ada Emelie": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Axelssen, Thorvald Willy Helland": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Finseth, Ferdinand": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Flem, Daniel Thye": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Flem, Ingrid Aurora": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Gausvik, Amanda": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Gullaksen, Thelion Alexander": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Hisdal-Fossdal, Evelyn": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Hovden, Elvira Maria": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Kadereya, Ali Mohmmad": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Nordbø, Vilma Sjøstrøm": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Nur, Nasra Hubi Abdirisaq": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Pedersen, Markus": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Schwarz, Georg Eik": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Skjelderup, Sander Konrad Liknes": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Skogrand-Arias, Aurora": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Skuterud, Jens Husaas": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Sotnedal, Elise Domansky": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Sudalaimuthu, Yalini": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },
    "Sødal, Iben Heltne": { startTrinn: 1, startKlasse: 'C', startAar: 2025 },

    // 2. TRINN (Startet 2025)
    "Al-Shalah, Kaiss": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Banouni, Sidra": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Chatat, Adm": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Da Cruz Aleixo, Ariana Maria": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Eidsaa, Vilhelm August Bragdø": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Fjellaker, Sara Rysstad": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Follerås, Emil Beqiraj": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Gabrielsen, Ivy Vinter Paddon": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Haugebo, Lucas Coward": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Jaglanian, Nova Nerhus": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Jakobsen, Kian": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Jones, Max Borgan": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Kianfar, Melora": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Moland-Krasniqi, Elian": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Ringsby, Konrad Langerud": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Solstad, Nathalie Senada": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Sørhus, Ruth": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Sørvig, Kristian Haakon": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Tabeth, Iman Said": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Viken, Madeleine Skarning": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Vingerhagen, Bjørn Flaat": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Wojtkiewicz, Maksymilian": { startTrinn: 2, startKlasse: 'A', startAar: 2025 },
    "Andersen, Noah Nøvik": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Arntsen, Emil Loland": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Axelssen, Lauritz Helland": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Børresen, Theodor Strand": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Chhoeuk, Riley": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Dahl, Kirsti Toft": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Dybedal, Leander Dufke": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Eid, Henrik Hamnes": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Forsaa-Nilsen, Othilie": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Hansen, Kevin Forslund": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Juliussen, Kaja Salcher": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Mogstad, Lilly Wikören": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Myren, Olai": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Nydal, Sonja": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Pettersen, Jett Paul": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Rai, Aaron": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Sergejev, Viktor": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Winther-Gulla, Gustav": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Zagarnauskas, Benas": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Øvland, Mats Brevig": { startTrinn: 2, startKlasse: 'B', startAar: 2025 },
    "Ghebremeskel, Mathias Tesfagabir": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Grindheim, Emilie Homme": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Grindheim, Mathias Homme": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Gundersen, Ellinor Mersland": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Habte, Hanna Epherm": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Hauge, Hermine": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Haugen, Johannes Ross": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Keleta, Sara Merhawi Kiflay": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Lauvnes, Alfred Widerøe": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Mangen, Lavrans": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Mortensen, Julia Rudi": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Nabiyar, Yosra": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Osnes, Leander": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Qadiri, Anja": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Ringstad, Simon": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Rosen, Yohan Andresen": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Vinknes, Franki Thurgood": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },
    "Vu, Matheo Hieu": { startTrinn: 2, startKlasse: 'C', startAar: 2025 },

    // 3. TRINN (Startet 2025)
    "Alieksieiev, Artem": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Bakke, Theo": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Bredsdorff, Josefine Sofie": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Fredriksen, Tomine Andresen": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Gudane, Ziham Ibrahim": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Gundersen, Michelle": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Iversen, Christina": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Kleba-Næss, Gabriel Anker": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Langåker, Noah": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Mydland, Storm": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Nabiyar, Ahmad": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Nygaard, Marcus Chang Tran": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Ravnaas, Elvira": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Selmer, Mina": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Skotnes, William": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Svensen, Daniel": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Sørvig, Céline Sophie": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Timenes, Amalie": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Timenes, Mathilde": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Tvedt, Selia": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Ytfesah, Sara Teklahaimanot": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Aagren, Louise Krossen": { startTrinn: 3, startKlasse: 'A', startAar: 2025 },
    "Bøgwald-Valbuena, Nathalie Kate": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Chhoeuk, Ask Tveter": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Ellingsen, Mia Fredheim": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Haugnes, Mathilde": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Hunstad-Lende, Nikolai": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Isaksen, Finnlay Tim": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Keleta, Davina Weldezghi": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Kårtveit-Torgersen, Olve": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Malik, Alaya": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Martinsen, Celine": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Meyer, Margot Megan Gyslene": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Myre, Jakob Norvald": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Nilsen, Filip Mål": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Nordheim, Jenny Høsteland": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Nyhus, Martin Mosland": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Opthun, Jens Oskar": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Pedersen, John Pål": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Seeber, Ella": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Shabanaj, Noah": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Skilbrei, Ella": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Skjelderup, Helge Elias Liknes": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Torland, Oliver Lystvet": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Velure, Magnus Aschim": { startTrinn: 3, startKlasse: 'B', startAar: 2025 },
    "Ali, Tala Yaser": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Bølstad, Synne Michaelsen": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Ebrahimpour, Nora Lavin": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Ege, Thea Sangereid": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Finseth, Sebastian": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Fredly, Adrian": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Holm, Mathea Khalili": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Hornnes, Leanne Jonassen": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Jeffs, Iben Noelle Mendoza": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Mangen, Olina": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Moland-Krasniqi, Alina": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Omestad, Ludvig Vang": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Peersen-Farhat, Jamil": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Riste, Ada-Emilie Josefsen": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Roland, Denise Andrade": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Roland, Leana Andrade": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Skogen, Albert": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Skretting, Daniel": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },
    "Øverland, Thomas": { startTrinn: 3, startKlasse: 'C', startAar: 2025 },

    // 4. TRINN (Startet 2025)
    "Al-Shalah, Cilin": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Andersen, Aksel Catin": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Askland, Jone": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Barria, Tilla Angelica": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Bye, Henrik Alexander Stokkelien": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Campos-Betancur, Lucas Alberto": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Chatat, Ellen": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Gundersen, Frida Mersland": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Hammersmark, Jens Dahl": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Hanslien-Bergstad, Elise": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Haugen, Tobias Ross": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Hussein, Hishaam Abdi": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Lien-Dahl, Iben Sørbotten": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Mahamud, Jibril Mahdi": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Noshaj, Angelos": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Obaid, Zeneddin": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Reinhardtsen, Marie": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Reinhardtsen, Oskar": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Soy, Kiean Villhjar Andersen": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Tvedt, Lucas Chhorm": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Vinknes, Olli Thurgood": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Wrånes, Anne Eivindson": { startTrinn: 4, startKlasse: 'A', startAar: 2025 },
    "Ali, Azaan": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Benonisen, Marlene": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Fretland, Emma Huang": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Gjømle, Siri Breivik": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Haugebo, Adrian Coward": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Hussain, Wasna": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Igland, Theodor Andersen": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Jakobsen, Leo": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Johansen, Sebastian": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Khan, Sufyan": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Lindebø, Leopold": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Mumtaz, Sofia Yasser": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Rege, Stella Amalie": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Sajjad, Hadi": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Skeie, Edvard Aagaard": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Skåra-Sladojevic, Emilia": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Smedsland, Erik Wathne": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Stranden, Jakob": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Sørhus, Oline": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Wadsworth, Liam Jeremiah": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Øvland, Erle Brevig": { startTrinn: 4, startKlasse: 'B', startAar: 2025 },
    "Albrecht, Wilhem Herdal": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Bisseth-Isefjær, Emily Alida": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Bobowski, Kacper": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Diser, Vilde Navjord": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Dzakic, Danis": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Gitlestad, Emily": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Hansen, Nicklas Løvheim": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Jones, Astrid Borgan": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Klausen, Benjamin Tørressen": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Mouniri, Tamina": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Nordbø, Alfred Sjøstrøm": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Nydal, Vårin": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Nygård-Andersen, Hedda": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Pettersen, Iben Wiksten": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Rugholm, Liam Lidi": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Sveindal, Robin Zamora": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Sørnes, Nathaniel René": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Terjesen, Ludvig Rosåsen": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },
    "Aarstøl, Sigurd Jacobsen": { startTrinn: 4, startKlasse: 'C', startAar: 2025 },

    // 5. TRINN (Startet 2025)
    "Aurebekk, Markus": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Bakken, Celine Christoffersen": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Beckmann, Tønnes Ljosdal": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Grimsby, Olivia Louise Haugen": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Hansen, Johannes": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Haugland, Emil": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Hollerud, Ida": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Johnsen, Markus Strandberg": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Keskin, Isak August Hanssen": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Lande, Nore Reistad": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Markham, Sofie": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Radojcic, Milan": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Riste, Alida-Angelica Josefsen": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Roland, Amila Andrade": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Sharifi, Solin": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Solberg, Emilie Hodne": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Sunnhordvik, Sanne": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Sørensen, William Arthur": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Thesen, Astrid": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Vu, Nicklas Hy": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Wiland-Svingen, Leah": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Wojtkiewicz, Natalia": { startTrinn: 5, startKlasse: 'A', startAar: 2025 },
    "Axelssen, Carl Alfred Helland": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Benestad, Kaja": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "El Hammani, Elias": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Fagerland, Herman Flak": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Haga, Sebastian": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Hansen, Kaja-Malene Forslund": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Haye, Abel Pedersen": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Ilyas, Sahal": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Juliussen, Dennis Salcher": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Jørgensen, Sofia Vogt": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Keleta, Diana Weldezghi": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Mckeever, Thomas Bjunes": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Mæland, Andrina": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Nilsen, Julia Mål": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Pedersen, Inea Sofie Falk": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Phillips, Oliver": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Schwarz, William Eik": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Sergejeva, Veronika": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Wennerberg, Sigurd Litland": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Westerlund, Molly Wehus": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Zagarnauskas, Henris": { startTrinn: 5, startKlasse: 'B', startAar: 2025 },
    "Andersen-Fleming, Celina": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Azhar, Muhammad Durab": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Bastlien-Joakimsen, Tinde": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Bostrøm, Jenny Lædre": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Bragdø, Lykke": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Eidsaa, Victor Emanuel Bragdø": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Ferris, Lucas Kenneth Norman": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Habarugira, Liam Matheo": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Jacobsen, Stella Thu": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Jasinski, Antoni": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Kallevik, Sofie Olsen": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Langåker, Liam": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Nur, Nuradin Abdirisaq": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Roest, Lyra Sofie Lindland": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Skagestad, Jonas": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Skjelderup, Matheo Michael Liknes": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Solberg, Jake Hunter": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Sotnedal, Tomine Domansky": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Strøm, Ørjan": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Strømme, Andreas Gundersen": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Timenes, Isak Døsvik": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Waly, Akam Kamal Sharif": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Øverland, Sara Margrete": { startTrinn: 5, startKlasse: 'C', startAar: 2025 },
    "Al-Shalah, Kassem": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Albert, Selene Ellinor": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Andersen Ocampo, Jean Pierre Henry": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Bakke, Thomas": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Balint, Emma": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Ege, Sofia Sangereid": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Eskeland, Fiona Marie": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Jaferi, Diana": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Khunsan, Sirithon": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Kianfar, Leo": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Kopperud, Sander Lunde": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Langeland, Annie Hegland": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Solli, Martine Stenberg": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Thorsteinsson, Aron Jon": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Tvedt, Theodor": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },
    "Wennberg-Brown, Mikayla Semine": { startTrinn: 5, startKlasse: 'D', startAar: 2025 },

    // 6. TRINN (Startet 2025)
    "Andersen, Aleksander Catin": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Andersen, Vetle": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Blekesaune, Karina Dusumbaeva": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Eftevåg, Johannes Kløckner": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Ellingsen, William Fredheim": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Fredly, Andreas": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Habte, Mathias Epherm": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Haidari, Matin": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Hana, Ari": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Hauge, Lykke Layan": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Larsen, Natalie Beatrice": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Legreid, Isabelle Soares": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Mikkelsen, Elias Timenes": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Mydland, Viljar": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Nygård-Andersen, Oda": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Paloka, Armper Or Arber": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Rasmussen, Jonas Juhl": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Ravnaas, Mille Aurora": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Roest, Aksel Lindland": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Timenes, Thea": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Vang-Halaas, Iben": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Ytfesah, Noah Teklahaimanot": { startTrinn: 6, startKlasse: 'A', startAar: 2025 },
    "Almedal, Martin Angelsen": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Andersen, Ellie": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Birkeland, Jarle Vieira": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Diser, Vebjørn Navjord": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Fredheim, Jakob Greibesland": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Gudane, Noradin Ibrahim": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Helleseng, Cornelia": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Hoel, Caitlyn Angelina": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Isachsen, Marie Ropstad": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Iversen, Marcus": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Lindebø, Tidemann": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Schlezinger, Umi Emilia": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Smedsland, Johan Wathne": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Solheim, Julie": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Toleikis, Viljamas": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Torland, Aurora Lystvet": { startTrinn: 6, startKlasse: 'B', startAar: 2025 },
    "Andersen, Oliver Nøvik": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Axelssen, Ingeborg Adele Helland": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Bondestad, Daniel": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Dahl-Jakobsen, Maja-Eline": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "El Hammani, Adam": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Gjerstad, Martin Leland": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Gundersen, Marcus Haugland": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Gyland, Chris Olai": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Haileselase, Eliana Liul": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Landa, Nora Rose Sandvær": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Lauvrak, Sander Årnes": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Nilsen, Alexandra Gudding": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Nordbø, Oskar Sjøstrøm": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Nur, Nasrudin Abdirisaq": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Opthun, Emmy": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Pettersen, Brage Wiksten": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Riise, Lucas Lindset": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Sarwar, Ibrahim": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Shadiev, Umar Magomedovich": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Wehus-Furø, Phillip": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },
    "Aas, Dennis Lohne": { startTrinn: 6, startKlasse: 'C', startAar: 2025 },

    // 7. TRINN (Startet 2025)
    "Apeland, Charlotte Dybvik": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Apeland, Olaus Dybvik": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Azhar, Mubeen": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Bye, Aksel Stokkelien": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Eidsaa, Vincent Andreas Bragdø": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Frøvold, Henrik Karstensen": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Gehrken, Johann Ensby": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Jensen, Jennie Austenå": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Kjelsrud, Iben Forus": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Kleba-Næss, August Anker": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Martinsen, Vincent": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Mydland, Brage": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Myre, Ingrid Anea": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Reinhardtsen, Oline": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Roland, Adelen Andrade": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Rugholm, Eline Lidi": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Ruiz-Flaten, Saray": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Skotnes, Nicklas": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Strøm, Jørgen": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Timenes, Jakob Døsvik": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Vorland-Langmyr, Kim Andrè": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Wdowiak, Julia Aleksandra": { startTrinn: 7, startKlasse: 'A', startAar: 2025 },
    "Albrecht, Cornelius Herdal": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Andersen, Emma Sæterdal": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Bjornes, Casper Brådland": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Bredsdorff, Tobias": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "De Lange, Marcus Eikrem": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Drivdal, Håkon": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Fagerland, Klara Flak": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Grimsby, August Haugen": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Jacobsen-Bull, Johan": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Langnes, Syver Eiklid": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Lindebø, Georg": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Martinsen, Krisztian Hagen": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Mumtaz, Iman Yasser": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Nguyen, Sebastian Eklund": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Omestad, Maiken Vang": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Stranden, Nellie Hermine": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Sudalaimuthu, Yogi": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Wilkens, Herman Iversen": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Øverland, Sofia": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Aanensen, Noah Nyhus": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Aarstøl, Brage Jacobsen": { startTrinn: 7, startKlasse: 'B', startAar: 2025 },
    "Albrigtsen, Kristian Tengesdal": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Claveau, Eilin": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Habtay, Camilla Tekle": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Hansen, Lena-Emilie Forslund": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Haye, Anna Pedersen": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Håkedal, Julie Magnussen": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Isachsen, Sofie Ropstad": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Johannessen, Nikolai": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Keleta, Mathias Weldezghi": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Mckeever, Theo Bjunes": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Moland-Krasniqi, Leona": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Nilsen, William Mål": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Qejji, Mareta Ammanuel": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Seilen, Lasse Emrik": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Selmer, Joel": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Strand, Lykke": { startTrinn: 7, startKlasse: 'C', startAar: 2025 },
    "Wennberg-Brown, Kaiden Gabriel": { startTrinn: 7, startKlasse: 'C', startAar: 2025 }


// 7. TRINN (Startet 2024)

// Klasse 7a
"Diaz, Matias Leonel Johansen": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Dzakic, Dina": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Eidsaa, Synne Marie Gumpen": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Farooq, Ahmed Omar": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Fiseha, Samuel Gebriel": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Flom, Amandus Heggernes": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Gitlestad, Benjamin": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Hauge, Nea Folden": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Haugland, Linus": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Jørgensen, Nora Vogt": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Kristensen, Silje Marie": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Magnus, Elisa": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Omdahl, Robin Rypestøl": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Robstad, Gabriella Amelie Morozova": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Seeber, Dafne": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Solberg, Lukas Hodne": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Som, Danny": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Westerlund, Laura Wehus": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },
"Aas, Emil Lohne": { startTrinn: 7, startKlasse: 'A', startAar: 2024 },

// Klasse 7b
"Ali, Mehd": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Bostrøm, Samuel Lædre": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Gjerstad, Mari Leland": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Hammersmark, Emilia Dahl": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Haugen, Casper Ross": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Jasinski, Jakub": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Kadereya, Salam": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Larsen, Kristianne Elise": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Mikkelsen, Mats Timenes": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Nikseresht, Arya": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Olsen, Kim Marius Berentsen": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Rasmussen, Julia Elisabeth": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Rypestøl, Herman Skofteland": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Skagestad, Sarah": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Skogerbø, Ludvig Hestenes": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Solberg, Olai": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Solberg, Sienna": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Sor, Kathrine": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Torp, Simon Thorgersen": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Vågen, Julie": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },
"Østmoe, Marie Tallaksen": { startTrinn: 7, startKlasse: 'B', startAar: 2024 },

// Klasse 7c
"Bondestad, Mille": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Brennan, Liam James": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Fossdal, Alisha Humaira": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Gjømle, Jonas Breivik": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Haraldstad, Emil Strømstad": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Kopperud, Sebastian Lunde": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Kvalvik, Christina": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Letek, Lena Emilia": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Mykjåland, Matheo": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Nguyen, Sarah": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Radojcic, Mihailo": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Ribe, Johan": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Sangachin, Noah": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Schaathun, Nathalie": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Thesen, Joar": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Thorsteinsdottir, Aria Osk": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Tomter, Filippa Sofia": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Trusin, Alexander": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Vestbø, Magnus Crogh": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },
"Waly, Anas": { startTrinn: 7, startKlasse: 'C', startAar: 2024 },

// Klasse 7d
"Ali, Mohamad Yaser": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Aurebekk, Julie": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Bjørndal, Vivill Myhre": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Chhorn, Linneth Isabell Tangen": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Duncan, Alexa-May": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Furulund-Skogestad, Kristian": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Gajic, Marko": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Hunstad-Antonsen, Tobias": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Lauvnes, Ulrik Widerøe": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Lyche, Konrad Buxrud": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Lågstad, Max Aaserud": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Mjåvatn-Caspersen, Marius": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Pedersen, Iris Amalie Falk": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Pepaj, Neo": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Solheim, Natalie": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Stausland, Mia Stokke": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Sunnhordvik, Jesper": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Tvedt, Liam": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Vu, Alexander Theodor Hoang": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Øhman, Fabian Putra": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },
"Aagren, Andrea Krossen": { startTrinn: 7, startKlasse: 'D', startAar: 2024 },

};
